name: Publish hugegraph-computer images

on:
  push:
    branches:
      - master
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Mapping env
        uses: kanga333/variable-mapper@master
        with:
          key: "${{github.event_name}}"
          map: |
            {
              "push": {
                "FRAMEWORK_IMAGE_URL": "hugegraph/hugegraph-computer-framework:latest",
                "ALGORITHM_IMAGE_URL": "hugegraph/hugegraph-computer-based-algorithm:latest",
                "OPERATOR_IMAGE_URL": "hugegraph/hugegraph-computer-operator:latest"
              },
              "release": {
                "FRAMEWORK_IMAGE_URL": "hugegraph/hugegraph-computer-framework:${{ github.ref_name }}",
                "ALGORITHM_IMAGE_URL": "hugegraph/hugegraph-computer-based-algorithm:${{ github.ref_name }}",
                "OPERATOR_IMAGE_URL": "hugegraph/hugegraph-computer-operator:${{ github.ref_name }}"
              }
            }

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ''
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Build Project
        run: bash computer-dist/builddocker.sh

      - name: Build images
        run: |
          PROJECT_VERSION=$(mvn -f "./pom.xml" -q -N \
          org.codehaus.mojo:exec-maven-plugin:1.3.1:exec \
          -Dexec.executable='echo' -Dexec.args='${project.version}')

          docker tag hugegraph/hugegraph-computer-framework:${PROJECT_VERSION} ${{ env.FRAMEWORK_IMAGE_URL }}
          echo "FROM ${{ env.FRAMEWORK_IMAGE_URL }}
          LABEL maintainer='HugeGraph Docker Maintainers <hugegraph@googlegroups.com>'
          COPY target/computer-algorithm-*.jar /opt/jars/computer-algorithm-based.jar
          ENV JAR_FILE_PATH=/opt/jars/computer-algorithm-based.jar" | \
          docker build -t ${{ env.ALGORITHM_IMAGE_URL }} -f - ./computer-algorithm

          docker build -t ${{ env.OPERATOR_IMAGE_URL }} -f computer-k8s-operator/Dockerfile ./computer-k8s-operator

      - name: Docker images
        run: docker images

      - name: Publish
        run: |
          docker push ${{ env.FRAMEWORK_IMAGE_URL }}
          docker push ${{ env.ALGORITHM_IMAGE_URL }}
          docker push ${{ env.OPERATOR_IMAGE_URL }}
