name: publish hugegraph-computer images

on:
  push:
    branches:
      - master
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Mapping env
        uses: kanga333/variable-mapper@master
        with:
          key: "${{github.event_name}}"
          map: |
            {
              "push": {
                "FRAMEWORK_IMAGE_URL": "hugegraph/hugegraph-computer-framework:latest",
                "ALGORITHM_IMAGE_URL": "hugegraph/hugegraph-builtin-algorithms:latest",
                "OPERATOR_IMAGE_URL": "hugegraph/hugegraph-computer-operator:latest"
              },
              "release": {
                "FRAMEWORK_IMAGE_URL": "hugegraph/hugegraph-computer-framework:${{ github.ref_name }}",
                "ALGORITHM_IMAGE_URL": "hugegraph/hugegraph-builtin-algorithms:${{ github.ref_name }}",
                "OPERATOR_IMAGE_URL": "hugegraph/hugegraph-computer-operator:${{ github.ref_name }}"
              }
            }

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: ''
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Install JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Build images
        env:
          TRAVIS_DIR: computer-dist/src/assembly/travis
        run: $TRAVIS_DIR/build-images.sh ${{ env.FRAMEWORK_IMAGE_URL }} ${{ env.ALGORITHM_IMAGE_URL }} ${{ env.OPERATOR_IMAGE_URL }}

      - name: Docker images
        run: docker images

      - name: Publish
        run: |
          docker push ${{ env.FRAMEWORK_IMAGE_URL }}
          docker push ${{ env.ALGORITHM_IMAGE_URL }}
          docker push ${{ env.OPERATOR_IMAGE_URL }}
